# instagram
INSTA_USERNAME = "epigenety"
INSTA_PASSWORD = "KanasutaEPIGENETY27!"
INSTA_ACCESS_TOKEN = "IGQVJWdEdJQ3RLTlpqZA25ZAbzFyV1ZAjUDQ0X2ZALWjVjTHdJY2ttWkJ4YmVzRF9MVDdXYzFCakZAPd25sOVpVZATJ1V0VQdkl6ZAmxtRFZAJTWcxZAWZAySHp4dUQzb3Iza21KOWVYMHFkSEVxNVIyYlVENFlZAZAwZDZD"

# open ai
OPENAI_API_KEY = "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"

# API endpoint for DALL-E
DALL_E_URL = "https://api.openai.com/v1/images/generations"
